services:
  portainer-ce:
    ports:
      - 9999:9000
    container_name: portainer_zh-cn
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/portainer_zh-cn:/data
    image: 6053537/portainer-ce
    network_mode: bridge
networks:
  bridge:
    external: true
