services:
  portainer-ce:
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/portainer:/data
    image: portainer/portainer-ce:latest
    network_mode: bridge
networks:
  bridge:
    external: true
