services:
    sun-panel:
        image: 'hslr/sun-panel:latest'
        container_name: sun-panel-1
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - /opt/docker/sun-panel:/app/conf'
        privileged: true
        ports:
            - '3002:3002'
        restart: always
